version: '3.1'
services:
  mongo:
    image: 'mongo'
    container_name: 'mongo-database-test'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - '27017-27019:27017-27019'